#!/bin/bash
mkdir issue_$1
cp ejemplo/ejemplo.py issue_$1/issue_$1.py
cp ejemplo/ejemplo.sql issue_$1/issue_$1.sql
echo "#$1    post    issue_$1/issue_$1.sql" >> ./TODO
echo "#$1    post    issue_$1/issue_$1.py"  >> ./TODO
